$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)

PRODUCT_DEVICE := X100
PRODUCT_NAME := omni_X100
PRODUCT_BRAND := DOOGEE
PRODUCT_MODEL := X100
PRODUCT_MANUFACTURER := DOOGEE
PRODUCT_BOARD := mt6580